# .gitpod.yml
tasks:
  - name: Backend Setup
    init: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
      # In .gitpod.yml, under the 'Backend Setup' task, inside the 'init' block:

      echo "export DATABASE_URL=\"postgresql://project_user:PMU#1234@localhost:5432/project_tracker_db\"" >> ~/.bashrc
      echo "export SECRET_KEY=\"054f7713d49a4a7873119d7bd9611d23\"" >> ~/.bashrc
      echo "export FASTAPI_BACKEND_URL=\"http://localhost:8000\"" >> ~/.bashrc # <-- ADD THIS LINE
      source ~/.bashrc # Load new env vars
      python -c "from backend.database import Base, engine; Base.metadata.create_all(bind=engine)"
    command: |
      echo "Starting FastAPI backend..."
      uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  - name: PostgreSQL Setup
    init: |
      sudo service postgresql start
      sudo -u postgres psql -c "CREATE DATABASE project_tracker_db;"
      # !!! CHANGE THIS PASSWORD !!! Use the same strong password as in DATABASE_URL above.
      sudo -u postgres psql -c "CREATE USER project_user WITH PASSWORD 'PMU#1234';"
      sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE project_tracker_db TO project_user;"
    command: |
      echo "PostgreSQL is running."

ports:
  - port: 8000
    onOpen: open-preview # Opens the FastAPI docs in a preview window
  - port: 5432 # PostgreSQL default port, Gitpod exposes it automatically
    onOpen: ignore